using System;
using RestaurantReviews.Domain;
using RestaurantReviews.DataAccess.Entities;
using System.Collections.Generic;
using System.Linq;


namespace RestaurantReviews.DataAccess
{
    /// <summary>
    /// Repoistory class for making adding, removing and making changes to the information in the database
    /// </summary>
    public class Repository : IRepository
    {

        
        private readonly RestaurantReviewContext _context;
        /// <summary>
        /// constructor, connects to database using DB context generated by Microsoft Entity Framework
        /// </summary>
        /// <param name="context"> the DBContext object</param>
        public Repository(RestaurantReviewContext context)
        {
            _context = context;
        }

        /// <summary>
        /// searches restauraunts by the name column in DB
        /// </summary>
        /// <param name="name">search string</param>
        /// <returns>List of restaurants with matching string in their name</returns>
        public List<Domain.Restaurant> SearchRestaurantsName(string name)
        {
            List<Domain.Restaurant> list = _context.Restaurants.Select(
                Restaurant => new Domain.Restaurant(Restaurant.Id, Restaurant.Name, Restaurant.Address, Restaurant.Zip)
            ).ToList();
            List<Domain.Restaurant> query = list.Where(Restaurant => Restaurant.Name.ToLower().Contains(name.ToLower())).ToList();


            return query;
        }

        /// <summary>
        /// searches restaurants by address column in DB
        /// </summary>
        /// <param name="address">search string</param>
        /// <returns>List of restaurants with matching string in their name</returns>
        public List<Domain.Restaurant> SearchRestaurantsAddress(string address)
        {
            List<Domain.Restaurant> list = _context.Restaurants.Select(
                Restaurant => new Domain.Restaurant(Restaurant.Id, Restaurant.Name, Restaurant.Address, Restaurant.Zip)
            ).ToList();
            List<Domain.Restaurant> query = list.Where(Restaurant => Restaurant.Address.ToLower().Contains(address.ToLower())).ToList();


            return query;
        }

        /// <summary>
        /// searches restaurants by zip column in DB
        /// </summary>
        /// <param name="zip">zip to search as an integer</param>
        /// <returns>list of restaurants with matching zip</returns>
        public List<Domain.Restaurant> SearchRestaurantsZip(int zip)
        {
            List<Domain.Restaurant> list = _context.Restaurants.Select(
                Restaurant => new Domain.Restaurant(Restaurant.Id, Restaurant.Name, Restaurant.Address, Restaurant.Zip)
            ).ToList();
            List<Domain.Restaurant> query = list.Where(Restaurant => Restaurant.Zip == zip).ToList();


            return query;
        }

        /// <summary>
        /// adds new customer information to DB
        /// </summary>
        /// <param name="customer">a new customer object, without value for primary key ID</param>
        /// <returns>customer object</returns>
        public Domain.Customer AddCustomer(Domain.Customer customer)
        {
            _context.Customers.Add(
                new Entities.Customer
                {
                    Name = customer.Name,
                    Pass = customer.Pass,
                    Phone = customer.Phone,
                    Email = customer.Email,
                    IsAdmin = customer.Admin
                }
            );
            _context.SaveChanges();

            return customer;
        }
        /// <summary>
        /// adds a new restaurant's infromation to DB
        /// </summary>
        /// <param name="restaurant">new restaurant object, without value for primary key ID</param>
        /// <returns></returns>
        public Domain.Restaurant AddRestaurant(Domain.Restaurant restaurant)
        {
            _context.Restaurants.Add(
                new Entities.Restaurant
                {
                    Name = restaurant.Name,
                    Address = restaurant.Address,
                    Zip = restaurant.Zip
                }
            );
            _context.SaveChanges();

            return restaurant;
        }
        /// <summary>
        /// Gets a restaurant reviews by its primary key ID orders reviews by date (most recent)
        /// </summary>
        /// <param name="Id">ID primary key of restauarant</param>
        /// <returns>list of reviews with foreign key matching restaurant primary key</returns>
        public List<Domain.Review> FindRatingsByRestaurantId(int Id)
        {
            
            List<Domain.Review> list = _context.Reviews.Select(
                Review => new Domain.Review(Review.Id, Review.Stars, Review.CustomerId, Review.RestaurantId, Review.Comment, Review.LeftAt)
            ).ToList();
            List<Domain.Review> query = list.Where(Review => Review.RestaurantId == Id).OrderBy(Review => Review.Date).ToList();
            query.Reverse();
            return query;

        }
        /// <summary>
        /// Finds reviews made by specific customer orders reviews by date (most recent)
        /// </summary>
        /// <param name="customer">customer to find reviews for</param>
        /// <returns>list of reviews made by customer</returns>
        public List<Domain.Review> FindReviewsByCustomer(Domain.Customer customer)
        {

            List<Domain.Review> list = _context.Reviews.Select(
                Review => new Domain.Review(Review.Id, Review.Stars, Review.CustomerId, Review.RestaurantId, Review.Comment, Review.LeftAt)
            ).ToList();
            List<Domain.Review> query = list.Where(Review => Review.CustomerId == customer.Id).OrderBy(Review => Review.Date).ToList();
            query.Reverse();
            return query;
        }

        /// <summary>
        /// Search customers by name
        /// </summary>
        /// <param name="name">search string</param>
        /// <returns>list of customers with matching string in name, case sensitive</returns>
        public List<Domain.Customer> SearchCustomers(string name)
        {
            List<Domain.Customer> list = _context.Customers.Select(
                Customer => new Domain.Customer(Customer.Id, Customer.Name, Customer.Pass, Customer.Phone, Customer.Email, Customer.IsAdmin)
            ).ToList();
            List<Domain.Customer> query = list.Where(Customer => Customer.Name.Contains(name)).ToList();


            return query;
        }

        /// <summary>
        /// gets a customer by their primary key ID
        /// </summary>
        /// <param name="Id">Primary key ID for customer in DB</param>
        /// <returns>returns customer with matching ID, returns new customer object if none exists</returns>
        public Domain.Customer GetCustomerById(int Id)
        {
            Entities.Customer foundCustomer = _context.Customers
                .FirstOrDefault(customer => customer.Id == Id);
            if (foundCustomer != null)
            {
                return new Domain.Customer(foundCustomer.Id, foundCustomer.Name, foundCustomer.Pass, foundCustomer.Phone, foundCustomer.Email, foundCustomer.IsAdmin);
            }
            return new Domain.Customer();
        }

        /// <summary>
        /// Puts review in DB
        /// </summary>
        /// <param name="review">review object to be placed in DB</param>
        /// <returns>review object</returns>
        public Domain.Review LeaveReview(Domain.Review review)
        {
            _context.Reviews.Add(
                new Entities.Review
                {
                    CustomerId = review.CustomerId,
                    RestaurantId = review.RestaurantId,
                    Comment = review.textReview,
                    Stars = review.Stars,
                    LeftAt =review.Date
                }
            );
            _context.SaveChanges();

            return review;
        }

        /// <summary>
        /// Deletes a customer and all their reviews from DB
        /// </summary>
        /// <param name="custDel">customer to be delete</param>
        public void DeleteUser(Domain.Customer custDel)
        {
            List<Domain.Review> usersReviews = FindReviewsByCustomer(custDel);
            foreach (Domain.Review review in usersReviews)
            {
                DeleteReview(review);
            }
            Entities.Customer customerToDelete = _context.Customers.Single(customer => customer.Id == custDel.Id);
            _context.Entry(customerToDelete).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _context.Customers.Remove(customerToDelete);
            _context.SaveChanges();
        }

        /// <summary>
        /// Deletes a reviews from DB
        /// </summary>
        /// <param name="revDel">review to be deleted</param>
        public void DeleteReview(Domain.Review revDel)
        {

            Entities.Review reviewToDelete = _context.Reviews.Single(review => review.Id == revDel.Id);
            _context.Reviews.Remove(reviewToDelete);
            _context.SaveChanges();
        }

        /// <summary>
        /// deletes a restaurant and all its reviews from DB
        /// </summary>
        /// <param name="restDel">restaurant to be deleted</param>
        public void DeleteRestaurant(Domain.Restaurant restDel)
        {
            List<Domain.Review> restaurantReviews = FindRatingsByRestaurantId(restDel.Id);
            foreach (Domain.Review review in restaurantReviews)
            {
                DeleteReview(review);
            }
            Entities.Restaurant restaurantToDelete = _context.Restaurants.Single(restaurant => restaurant.Id == restDel.Id);
            _context.Restaurants.Remove(restaurantToDelete);
            _context.SaveChanges();
        }

        /// <summary>
        /// gets a customer by name
        /// </summary>
        /// <param name="name">name to search customer by</param>
        /// <returns>returns customer with name matching name string, returns new customer object if none is found</returns>
        public Domain.Customer GetCustomer(string name)
        {
            Entities.Customer foundCustomer = _context.Customers
                .FirstOrDefault(customer => customer.Name == name);
            if (foundCustomer != null)
            {
                return new Domain.Customer(foundCustomer.Id, foundCustomer.Name, foundCustomer.Pass, foundCustomer.Phone, foundCustomer.Email, foundCustomer.IsAdmin);
            }
            return new Domain.Customer();
        }
        /// <summary>
        /// gets a review by its primary key ID
        /// </summary>
        /// <param name="Id">Id of review</param>
        /// <returns>review with matching primary key, new review object if none exists</returns>
        public Domain.Review GetReviewById(int Id)
        {
            Entities.Review foundReview = _context.Reviews
                .FirstOrDefault(review => review.Id == Id);
            if (foundReview != null)
            {
                return new Domain.Review(foundReview.Id, foundReview.Stars, foundReview.CustomerId, foundReview.RestaurantId, foundReview.Comment, foundReview.LeftAt);
            }
            return new Domain.Review();
        }

        /// <summary>
        /// gets a restaurant by its primary key ID
        /// </summary>
        /// <param name="Id">Id of restaurant</param>
        /// <returns>restaurant with matching primary key, new restaurant object if none exists</returns>
        public Domain.Restaurant GetRestaurantById(int Id)
        {
            Entities.Restaurant foundRestaurant = _context.Restaurants
                .FirstOrDefault(restaurant => restaurant.Id == Id);
            if (foundRestaurant != null)
            {
                return new Domain.Restaurant(foundRestaurant.Id, foundRestaurant.Name, foundRestaurant.Address, foundRestaurant.Zip);
            }
            return new Domain.Restaurant();
        }

    }
}
