# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
     - main
  paths:
    include:
    - P1-Sean-Fitzmaurice
   
pr:
  branches:
    include:
    - main
  paths:
    include:
    - P1-Sean-Fitzmaurice

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: 'Project/RestaurantReviews.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 
    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        feedsToUse: 'select'
    - task: VisualStudioTestPlatformInstaller@1
      inputs:
        packageFeedSelector: 'nugetOrg'
        versionSelector: 'latestPreRelease'
      
    - task: SonarCloudPrepare@1
      displayName: Sonar Prepare
      inputs:
        SonarCloud: 'SONAR_TOKEN'
        organization: '210726-wvu-net-ext'
        scannerMode: 'MSBuild'
        projectKey: '210726-wvu-net-ext_P1-Sean-Fitzmaurice'
        projectName: 'P1-Sean-Fitzmaurice'
        
    - task: UseDotNet@2
      displayName: Dotnet SDK 5
      inputs:
        packageType: 'sdk'
        version: '5.x'
    
    - script: dotnet build --configuration Release
      displayName: dotnet build
      workingDirectory: 'Project'
      
    - task: SonarCloudAnalyze@1
      displayName: Sonar Analyze

    - task: SonarCloudPublish@1
      displayName: Sonar Public

    - script: dotnet publish
        --configuration Release
        --output $(Build.StagingDirectory)
      displayName: dotnet publish
      workingDirectory: 'Project'
