# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
     - main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/RestaurantReviews/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'VsTest - testAssemblies'
  inputs:
    testAssemblyVer2: |
     **\*Test*.dll
     !**\obj\**
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Revature-Project1/*.sln'
    feedsToUse: 'select'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: 'RestaurantReviews'
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'

- script: dotnet publish
    --configuration Release
    --output $(Build.StagingDirectory)
  displayName: dotnet publish
  workingDirectory: 'RestaurantReviews'

- task: SonarCloudPrepare@1
  displayName: Sonar Prepare
  inputs:
    SonarCloud: 'SONAR_TOKEN'
    organization: 210726-wvu-net-ext
    scannerMode: 'MSBuild'
    projectKey: 210726-wvu-net-ext_P1-Sean-Fitzmaurice




